export const AUTHENTICATION_ERROR = "AUTHENTICATION_ERROR";

export const USER_LOADING = "USER_LOADING";
export const USER_LOADED = "USER_LOADED";

export const LOGIN_FAILED = "LOGIN_FAILED";
export const LOGIN_SUCCESSFUL = "LOGIN_SUCCESSFUL";
export const LOGOUT_SUCCESSFUL = "LOGOUT_SUCCESSFUL";

export const REGISTRATION_FAILED = "REGISTRATION_FAILED";
export const REGISTRATION_SUCCESSFUL = "REGISTRATION_SUCCESSFUL";

export const RECEIVE_PRODUCTS = "RECEIVE_PRODUCTS";
export const RECEIVE_RECOMMENDED_PRODUCTS = "RECEIVE_RECOMMENDED_PRODUCTS";

export const RECEIVE_BOX = "RECEIVE_BOX";
export const ADD_BOX_ITEM = "ADD_BOX_ITEM";
export const REMOVE_BOX_ITEM = "REMOVE_BOX_ITEM";

export const RECEIVE_ORDERS = "RECEIVE_ORDERS";
export const ORDER_SUCCESSFUL = "ORDER_SUCCESSFUL";
export const ORDER_ERROR = "ORDER_ERROR";

export const QUESTIONNAIRE_ERROR = "QUESTIONNAIRE_ERROR";
export const GET_QUESTIONNAIRE = "GET_QUESTIONNAIRE";
export const QUESTIONNAIRE_SUBMIT_PROCESSING =
  "QUESTIONNAIRE_SUBMIT_PROCESSING";
export const QUESTIONNAIRE_SUBMIT_SUCCESS = "QUESTIONNAIRE_SUBMIT_SUCCESS";
