export const AUTHENTICATION_ERROR = "AUTHENTICATION_ERROR";

export const DELETE_NOTE = "DELETE_NOTE";
export const UPDATE_NOTE = "UPDATE_NOTE";
export const ADD_NOTE = "ADD_NOTE";
export const FETCH_NOTES = "FETCH_NOTES";

export const USER_LOADING = "USER_LOADING";
export const USER_LOADED = "USER_LOADED";

export const LOGIN_FAILED = "LOGIN_FAILED";
export const LOGIN_SUCCESSFUL = "LOGIN_SUCCESSFUL";
export const LOGOUT_SUCCESSFUL = "LOGOUT_SUCCESSFUL";

export const REGISTRATION_FAILED = "REGISTRATION_FAILED";
export const REGISTRATION_SUCCESSFUL = "REGISTRATION_SUCCESSFUL";

export const RECEIVE_PRODUCTS = "RECEIVE_PRODUCTS";

export const RECEIVE_BOX = "RECEIVE_BOX";
export const ADD_BOX_ITEM = "ADD_BOX_ITEM";
export const REMOVE_BOX_ITEM = "REMOVE_BOX_ITEM";

export const RECEIVE_ORDERS = "RECEIVE_ORDERS";
export const ORDER_SUCCESSFUL = "ORDER_SUCCESSFUL";
export const ORDER_ERROR = "ORDER_ERROR";
